[package]
name = "synccollection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = {version="*", features=["rt-multi-thread", "macros"]}
uuid = {version="*"}
chrono = {version="*"}
